### ISSUE TITLE
`matchName` throws TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by Narmdo** [yibn2008/find-process#30] opened 2019-10-27 22:58 UTC
I'm getting an issue caused by `text` within `matchName` being undefined.

Here's my stack trace.

```[main 2019-10-23 17:17:37.473] [error] TypeError: Cannot read property 'match' of undefined
    at o (...\node_modules\find-process\lib\find_process.js:25:1)
    at i.parseTable.filter (...\node_modules\find-process\lib\find_process.js:148:1)
    at Array.filter (<anonymous>)
    at ChildProcess.r.on (...\node_modules\find-process\lib\find_process.js:137:1)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

What would be causing this?

**Comment by mitchwilliamson** [comment] 2019-11-13 00:53
I'm unable to reproduce this myself, but it is causing issues for some of our users.

![image](https://user-images.githubusercontent.com/15311130/68722994-66f59980-060b-11ea-823d-ef779b5accf6.png)

We'll likely be resolving this by adding an `undefined` check in `matchName` in our own fork, but I'd imagine this is caused by a bug in the parsing of WMIC output in this library.

**Comment by Narmdo** [comment] 2019-11-15 05:36
I'm doing exactly that right now. Couldn't replicate myself either, but have had several users have this issue.

**Comment by yibn2008** [comment] 2019-11-15 06:07
I'll add an non-string check for matchName to avoid error

**Closed** 2019-11-15 06:12 UTC
